# render.yaml

services:
  - type: web
    name: vietnam-news-api
    env: python
    plan: free # Or your desired plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
